# Структуры данных

Работая с большим количеством одинаковых данных их удобно хранить в структурированном виде, что позволяет обращатся к ним систематизированно<br>

**Julia** поддерживает следующие структуры данных:
1. Кортежи (Tuples)
2. Словари (Dictionaries)
3. Массивы (Arrays)

<br>
Коротко их можно охарактеризовать следующим образом - массивы и кортежи являются упорядаченными структурами (доступ к элементам можно получить по их номеру), словари и массивы - редактируемые структуры.

## Кортежи

Мы можем создать кортеж путем помещения упорядоченой коллекции элементов в круглые скобки `( )`.

Синтаксис: <br>
```julia
(элемент1, элемент2, ...)
```


In [1]:
myfavoriteanimals = ("Пингвины", "Коты", "Сахарные летяги")

("Пингвины", "Коты", "Сахарные летяги")

Доступ к элемента осуществляется по их индексу,

In [2]:
myfavoriteanimals[1]

"Пингвины"

но поскольку кортежи нередактируемые, мы не можем изменить их элементы

In [3]:
myfavoriteanimals[1] = "Вомбаты"

LoadError: MethodError: no method matching setindex!(::Tuple{String, String, String}, ::String, ::Int64)

##  Именнованные кортежи

Начиная с версии 1.6 **Julia** поддерживает именнованные массивы, в которых каждый элемент кроме номера также имеет свое имя. Для добавления имени необходимо использовать `=` внутри кортежа:

```julia
(name1 = item1, name2 = item2, ...)
```

In [4]:
myfavoriteanimals_1 = (bird = "Пингвины", mammal = "Коты", marsupial = "Сахарные летяги")

(bird = "Пингвины", mammal = "Коты", marsupial = "Сахарные летяги")

Как и обычные кортежи, именнованные кортежи позволяют обращатся к элементам по номеру:

In [5]:
myfavoriteanimals_1[1]

"Пингвины"

Но так же к ним можно образатся по имени:

In [6]:
myfavoriteanimals_1.bird

"Пингвины"

## Словари

Для хранения набора парных данных удобно использовать словари. Для создания словаря необходимо использовать функцию `Dict()`.

Синтаксис:
```julia
Dict(ключ1 => значение1, ключ2 => значение2, ...)
```

Хороший пример - записная книжка, где каждому имени соответствует номер телефона.

In [7]:
myphonebook = Dict("Деннис" => "+7(977) 53-09-668", "Охотники за превидениями" => "555-2368")

Dict{String, String} with 2 entries:
  "Деннис"                   => "+7(977) 53-09-668"
  "Охотники за превидениями" => "555-2368"

В данном примере каждые имя и номер являются парой "ключ" и "значение". Мы можем узнать номер Денниса используяю соответствующий ключ

In [8]:
myphonebook["Деннис"]

"+7(977) 53-09-668"

Мы можем добавить новую запись в словарь просто путем присваивания

In [9]:
myphonebook["Жди меня"] = "8-800-700-84-36"

"8-800-700-84-36"

Теперь записная книжка выглядит следующим образом

In [10]:
myphonebook

Dict{String, String} with 3 entries:
  "Жди меня"                 => "8-800-700-84-36"
  "Деннис"                   => "+7(977) 53-09-668"
  "Охотники за превидениями" => "555-2368"

Удаление элементов осуществляется при помощи функции `pop!`

In [ ]:
pop!(myphonebook, "Жди меня")

In [12]:
myphonebook

Dict{String, String} with 3 entries:
  "Жди меня"                 => "8-800-700-84-36"
  "Деннис"                   => "+7(977) 53-09-668"
  "Охотники за превидениями" => "555-2368"

In [16]:
myphonebook["1"] = "one"

"one"

In [18]:
myphonebook[1] = "one"



LoadError: MethodError: Cannot `convert` an object of type Int64 to an object of type String
Closest candidates are:
  convert(::Type{String}, ::String) at essentials.jl:210
  convert(::Type{T}, ::T) where T<:AbstractString at strings/basic.jl:231
  convert(::Type{T}, ::AbstractString) where T<:AbstractString at strings/basic.jl:232
  ...

In [26]:
new_dict = Dict{Any, Any}(1 => "one", 2 => "two")

Dict{Any, Any} with 2 entries:
  2 => "two"
  1 => "one"

In [28]:
new_dict["string"] = "какая-то строка"

"какая-то строка"

In [30]:
new_dict

Dict{Any, Any} with 3 entries:
  "string" => "какая-то строка"
  2        => "two"
  1        => "one"

In [34]:
second_dict = Dict(1 => 3, 2 => "two", 2=>3 )

Dict{Int64, Any} with 2 entries:
  2 => 3
  1 => 3

In [24]:
a = 6
a = "string"

"string"

In [15]:
myphonebook

Dict{String, String} with 4 entries:
  "Жди меня"                 => "8-800-700-84-36"
  "1"                        => "one"
  "Деннис"                   => "+7(977) 53-09-668"
  "Охотники за превидениями" => "555-2368"

В отличии от кортежей и массивов, словари не упорядоченны, поэтому мы не можем обращатся к их элементам по индексу

In [11]:
myphonebook[1]

LoadError: KeyError: key 1 not found

In [31]:
keys(new_dict)

KeySet for a Dict{Any, Any} with 3 entries. Keys:
  "string"
  2
  1

В примере выше **Julia** считает, что вы пытаетесь обратиться к элементу с ключем `1`.

## Массивы

Как уже говорилось, в отличии от кортежей, массивы могут быть изменены, а в отличии от словарей - данные в массиве упорядочены.<br>
Самым простым способо определить массив является перечисление его элементов в квадратных скобках `[ ]`.

Синтаксис: <br>
```julia
[элемент1, элемент2, ...]
```

К примеру, мы можем создать массив студентов

In [35]:
students = ["Иванов", "Петров", "Васечкин", "Сидоров", "Солтыков-Щедрин"]

5-element Vector{String}:
 "Иванов"
 "Петров"
 "Васечкин"
 "Сидоров"
 "Солтыков-Щедрин"

После того, как массив создан, мы моем получить доступ к его элемента по их индексу. Индексация в **Julia** начинается с 1.

In [36]:
students[3]

"Васечкин"

Таким же образом, мы можем менять его элементы

In [38]:
students[3] = "Соломоненко"

"Соломоненко"

In [40]:
students

5-element Vector{String}:
 "Иванов"
 "Петров"
 "Соломоненко"
 "Сидоров"
 "Солтыков-Щедрин"

Так же, имеется несколько функции определяющих массив заданной формы:

In [41]:
ones_ = ones(4)

4-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0

In [42]:
zeros_ = zeros(4,2)

4×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [47]:
rands_ = rand(2,3,1)

2×3×1 Array{Float64, 3}:
[:, :, 1] =
 0.285587  0.395736  0.629546
 0.71194   0.979488  0.97498

Эти функции работают схожим образом - они возвращают массив заданного размера, состоящий из единиц, нулей или случайных чисел.<br>
Как можно было заметить, тип у них отличается: в первом случае это `Vector{Float64}`, во втором `Matrix{Float64}` и в третьем - `Array{Float64,3}`. На самом деле `Vector{T}` и `Matrix{T}` - это всего лишь псевдонимы для `Array{T,1}` и `Array{T,2}`, где `T` - это тип компонентов массива.

В **Julia** полезно заранее объявлять массив - это позволяет оптимизировать вычисления. Для этого существует универсальный конструктор массивов 

In [48]:
arr_1 = Array{Int64}(undef, 3,5)

3×5 Matrix{Int64}:
 263569920  253616208  253616208  253635456  255221264
         0          0          0          0          0
 253765728  253765728  253765728  253765728  253765728

Здесь `undef` - ключевое слово, которое означает, что массив элементы массива не иницализируются при ео объявлении. Сразу после объявления в них будет находиться "*мусор*" из памяти.<br>
В объявленный таким образом массив уже не получится занести элемент другой типа:

In [49]:
arr_1[1,1] = 3.5

LoadError: InexactError: Int64(3.5)

В случае, если заранее не известно, какого типа элементы могут храниться в массиве, в качестве типа можно указать `Any`

In [50]:
arr_2 = Array{Any}(undef, 4,4)

4×4 Matrix{Any}:
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef

In [51]:
fibonacci = Array{Float64}([1, 1, 2, 3, 5, 8, 13])

7-element Vector{Float64}:
  1.0
  1.0
  2.0
  3.0
  5.0
  8.0
 13.0

In [52]:
mixture = [1, 1, 2, 3, "Ted", "Robyn"]

6-element Vector{Any}:
 1
 1
 2
 3
  "Ted"
  "Robyn"

Для редактирования массивов так же имеются функции `push!` и `pop!`. `push!` добавляет элементы в конец массива, а `pop!` удаляет последний элемент из массива.

In [53]:
push!(fibonacci, 21)

8-element Vector{Float64}:
  1.0
  1.0
  2.0
  3.0
  5.0
  8.0
 13.0
 21.0

In [54]:
pop!(fibonacci)

21.0

In [ ]:
fibonacci

Поскольку массив - это тоже тип данных, мы можем определять массив массивов:

In [55]:
favorites = [["koobideh", "chocolate", "eggs"],["penguins", "cats", "sugargliders"]]

2-element Vector{Vector{String}}:
 ["koobideh", "chocolate", "eggs"]
 ["penguins", "cats", "sugargliders"]

При этом, они не обяаны быть совместимй размерности:

In [56]:
numbers = [[1, 2, 3], [4, 5], [6, 7, 8, 9]]

3-element Vector{Vector{Int64}}:
 [1, 2, 3]
 [4, 5]
 [6, 7, 8, 9]

Однако не следует путать их с двумерными массивами (или матрицами) - доступ к элементам осуществляется по разному

In [57]:
numbers[1][2]

2

In [58]:
numbers[1,2]

LoadError: BoundsError: attempt to access 3-element Vector{Vector{Int64}} at index [1, 2]

In [59]:
zeros_[2,2]

0.0

In [60]:
zeros_[2][2]

LoadError: BoundsError

**Будте остороны при копировании массивов!**

In [61]:
fibonacci

7-element Vector{Float64}:
  1.0
  1.0
  2.0
  3.0
  5.0
  8.0
 13.0

In [62]:
somenumbers = fibonacci

7-element Vector{Float64}:
  1.0
  1.0
  2.0
  3.0
  5.0
  8.0
 13.0

In [63]:
somenumbers[1] = 404

404

In [64]:
fibonacci

7-element Vector{Float64}:
 404.0
   1.0
   2.0
   3.0
   5.0
   8.0
  13.0

Редактирование `somenumbers` привело к изменению переменной `fibonacci`!

В данном примере мы, в де1ствительности, не копировали переменную `fibonacci`. Мы просто создали новую ссылку для доступа к объекту `fibonacci`.

Если нам необходимо создать компию массива `fibonacci`, необходимо использовать функцию `copy`.

In [65]:
# Для начала, восcтановим fibonacci
fibonacci[1] = 1
fibonacci

7-element Vector{Float64}:
  1.0
  1.0
  2.0
  3.0
  5.0
  8.0
 13.0

In [66]:
somemorenumbers = copy(fibonacci)

7-element Vector{Float64}:
  1.0
  1.0
  2.0
  3.0
  5.0
  8.0
 13.0

In [67]:
somemorenumbers[1] = 404

404

In [68]:
fibonacci

7-element Vector{Float64}:
  1.0
  1.0
  2.0
  3.0
  5.0
  8.0
 13.0

### Упражнения

#### 3.1 
Создайте массив `a_ray` с элементами `[1, 2, 3]`

In [78]:
a_ray = Array{Int64}([1, 2, 3])
push!(a_ray, 4)


4

Добавьте `4` в конец массива.

In [81]:
push!(a_ray, 4)
@assert a_ray == [1, 2, 3, 4]


LoadError: AssertionError: a_ray == [1, 2, 3, 4]

In [85]:
pop!(a_ray)

4

In [86]:
a_ray

3-element Vector{Int64}:
 1
 2
 3

и удалите ее

In [84]:
@assert a_ray == [1, 2, 3]

LoadError: AssertionError: a_ray == [1, 2, 3]

#### 3.2 
Добавьте в записную книжку `myphonebook` телефон пожарной `101`?

In [87]:
myphonebook["Пожарная"] = "101"

"101"

#### 3.3 
Создайте переменную `flexible_phonebook` , в которой могли бы хранится номера как в строковом, так и в численном виде, и добавьте туда номера *Денниса* и *Охотников за превидениями*.



In [88]:
flexible_phonebook = Dict{String, Any}("Dennis" => "1", "Kev" => "2")

Dict{String, Any} with 2 entries:
  "Kev"    => "2"
  "Dennis" => "1"

In [89]:
@assert typeof(flexible_phonebook) == Dict{String, Any}