# Факторизация матриц
## Содержание
1. $\mathbf{LU}$ - разложение
2. Разложение Холецкого ($\mathbf{LL'}$ - разложение)
3. $\mathbf{QR}$ - разложение
4. Спектральное разложение
5. Сингулярное разложение

## $\mathbf{LU}$ - разложение
$\mathbf{LU}$ - разложением называется разложение **квадратной** матрицы на произведение нижнетреугольной и верхнетреугольной матриц
$$
\mathbf{A = LU}\\
\begin{bmatrix}
        a_{11} & a_{12} & a_{13} & \ldots & a_{1n} \\
        a_{21} & a_{22} & a_{23} & \ldots & a_{2n} \\
        a_{31} & a_{32} & a_{33} & \ldots & a_{3n} \\
        \vdots & \vdots & \vdots & \ddots & \vdots \\
        a_{n1} & a_{n2} & a_{n3} & \ldots & a_{nn} \\ 
\end{bmatrix}
 = 
\begin{bmatrix}
        1 & 0 & 0 & \ldots & 0 \\
        l_{21} & 1 & 0 & \ldots & 0 \\
        l_{31} & l_{32} & 1 & \ldots & 0 \\
        \vdots & \vdots & \vdots & \ddots & \vdots \\
        l_{n1} & l_{n2} & l_{n3} & \ldots & 1 \\ 
\end{bmatrix}
\begin{bmatrix}
        u_{11} & u_{12} & u_{13} & \ldots & u_{1n} \\
        0 & u_{22} & u_{23} & \ldots & u_{2n} \\
        0 & 0 & u_{23} & \ldots & u_{3n} \\
        \vdots & \vdots & \vdots & \ddots & \vdots \\
        0 & 0 & 0 & \ldots & u_{nn} \\ 
\end{bmatrix}
$$


Если мы расспишем произведение $\mathbf{LU}$, то получится что матрица $\mathbf{A}$ равна:
$$
\begin{bmatrix}
        a_{11} & a_{12} & a_{13} & \ldots & a_{1n} \\
        a_{21} & a_{22} & a_{23} & \ldots & a_{2n} \\
        a_{31} & a_{32} & a_{33} & \ldots & a_{3n} \\
        \vdots & \vdots & \vdots & \ddots & \vdots \\
        a_{n1} & a_{n2} & a_{n3} & \ldots & a_{nn} \\ 
\end{bmatrix}
 = 
 \begin{bmatrix}
        u_{11}          & u_{22}                        & u_{23}                                        & \ldots & u_{1n} \\
        l_{21}u_{11}    & l_{21}u_{12} + u_{22}         & l_{21}u_{13} + u_{23}                         & \ldots & l_{21}u_{1n} + u_{2n} \\
        l_{31}u_{11}    & l_{31}u_{12} + l_{32}u_{22}   & l_{31}u_{13} + l_{32}u_{23} + u_{33}          & \ldots & l_{31}u_{1n} + l_{32}u_{2n} + u_{3n} \\
        \vdots          & \vdots                        & \vdots                                        & \ddots & \vdots \\
        l_{n1}u_{11}    & l_{n1}u_{12} + l_{n2}u_{22}   & l_{n1}u_{13} + l_{n2}u_{23} + l_{n3}u_{33}    & \ldots & \left( \sum_{i=1}^{n-1}{l_{ni}u_{in}} \right) + u_{nn} \\ 

 \end{bmatrix}

 $$

Из полученного выражения путем индукции можно записать выражения для элементов матриц $\mathbf{L}$ и $\mathbf{U}$
$$
    i = 1..n; \ j = i..n\\
    u_{ij} = a_{ij} - \sum_{k=1}^{i-1}{l_{ik}u_{kj}}\\
    l_{ji} = \left( u_{jj} \right)^{-1} \left( a_{ji} - \sum_{k = 1}^{i-1}{l_{jk}u_{ki}} \right)
$$

Используя приведенные формулы не составит труда написать функцию для расчета $\mathbf{LU}$ - разложения

In [53]:
function myLU(A::AbstractMatrix{<:Number})::Tuple{Matrix{Float64},Matrix{Float64}}
    
    N = size(A,1);
    L = zeros(Float64, N, N); U = zeros(Float64, N, N);
    for i in 1:N
        L[i,i] = 1; 
        for j in i:N
            U[i,j] = A[i,j] - sum(L[i,1:i-1]*U[1:i-1,j]');
        end
        for j in (i+1):N 
            L[j,i] = (A[j,i] - sum(L[j, 1:i-1]*U[1:i-1, i]')) / U[i,i]
        end
    end
    return (L, U)
end

myLU (generic function with 1 method)

In [48]:
A = rand(10,10)
L, U = myLU(A);
A

10×10 Matrix{Float64}:
 0.319819  0.674931   0.719025   0.480719   …  0.924169   0.341213  0.900015
 0.155998  0.801689   0.819516   0.980031      0.679624   0.323399  0.0691709
 0.632649  0.592221   0.274857   0.57692       0.383172   0.604286  0.798691
 0.32937   0.107871   0.0809883  0.48664       0.72159    0.727612  0.558679
 0.22552   0.0973996  0.891164   0.728927      0.292829   0.121931  0.546513
 0.286094  0.179631   0.347659   0.11656    …  0.0179565  0.126552  0.485476
 0.410653  0.626222   0.0230126  0.323847      0.720191   0.324789  0.554388
 0.361809  0.675038   0.450906   0.982612      0.442068   0.629949  0.181549
 0.170348  0.413294   0.180792   0.0781083     0.363283   0.240926  0.688911
 0.739863  0.687617   0.310349   0.990112      0.808886   0.309621  0.938345

In [49]:
U

10×10 Matrix{Float64}:
 0.319819  0.674931  0.719025  …   0.924169   0.341213    0.900015
 0.0       0.472478  0.468798      0.228843   0.156966   -0.369829
 0.0       0.0       2.14251       2.19609    1.38759     1.63232
 0.0       0.0       0.0          -1.71268   -0.643043   -1.01312
 0.0       0.0       0.0          -1.53109   -1.26318    -0.734561
 0.0       0.0       0.0       …  -0.088053   0.147137    0.0680025
 0.0       0.0       0.0           0.687234   0.0832258  -0.366284
 0.0       0.0       0.0           7.94715    2.86606     1.42305
 0.0       0.0       0.0           0.0       -1.71343    -0.289286
 0.0       0.0       0.0           0.0        0.0         3.6403

In [50]:
L

10×10 Matrix{Float64}:
 1.0        0.0        0.0        …    0.0       0.0       0.0      0.0
 0.487769   1.0        0.0             0.0       0.0       0.0      0.0
 1.97815   -3.55048    1.0             0.0       0.0       0.0      0.0
 1.02986   -2.2727     1.96968         0.0       0.0       0.0      0.0
 0.70515   -1.50631    1.66127         0.0       0.0       0.0      0.0
 0.894551  -1.79222    1.55761    …    0.0       0.0       0.0      0.0
 1.28402   -1.79283    0.80164         1.0       0.0       0.0      0.0
 1.13129   -1.31861    0.501633      -22.956     1.0       0.0      0.0
 0.532639  -0.418772  -0.0926111     -16.7439    7.28679   1.0      0.0
 2.31338   -4.16269    3.01943        26.6797  -14.6948   -1.05792  1.0

In [51]:
L*U

10×10 Matrix{Float64}:
 0.319819   0.674931    0.719025   …    0.924169    0.341213    0.900015
 0.155998   0.801689    0.819516        0.679624    0.323399    0.0691709
 0.632649  -0.342411    1.90039         3.21173     1.50525     4.72575
 0.32937   -0.378717    3.89512         3.0446      2.08473     3.96944
 0.22552   -0.235769    3.36014         1.98836     0.882511    2.91107
 0.286094  -0.243025    3.14021    …    3.14715     2.1392      3.71415
 0.410653   0.0195511   1.80029         3.0692      1.61927     2.85424
 0.361809   0.140527    1.27001        -6.15431     4.277      13.5042
 0.170348   0.161633   -0.0117594      45.7695     19.2899     17.4187
 0.739863  -0.405407    6.18107       -90.4894    -36.6677    -19.838

In [52]:
A - L*U

10×10 Matrix{Float64}:
  0.0          0.0        0.0       …    0.0        0.0         0.0
  0.0          0.0        0.0            0.0        0.0         0.0
  0.0          0.934632  -1.62553       -2.82856   -0.900966   -3.92706
  0.0          0.486588  -3.81413       -2.32301   -1.35712    -3.41076
  0.0          0.333168  -2.46898       -1.69553   -0.76058    -2.36456
  0.0          0.422656  -2.79255   …   -3.1292    -2.01264    -3.22868
  0.0          0.606671  -1.77727       -2.34901   -1.29448    -2.29985
  0.0          0.534511  -0.819108       6.59638   -3.64705   -13.3227
  0.0          0.25166    0.192551     -45.4062   -19.0489    -16.7298
 -1.11022e-16  1.09302   -5.87072       91.2983    36.9773     20.7764