# Решение СЛАУ прямыми методами
Системы линейных алгебраических уравнений выглядят так:
$$
 \left
\{\begin{gathered}
a_{11}x_1 + a_{12}x_2 + \dots + a_{1n}x_n = b_1 \\
a_{21}x_1 + a_{22}x_2 + \dots + a_{2n}x_n = b_2 \\
\cdots \\
a_{n1}x_1 + a_{n2}x_2 + \dots + a_{nn}x_n = b_n \\
\end{gathered}
\right.,
$$
где $x_1 \dots x_n$ – неизвестные, $a_1 \dots a_n$ – коэффициенты, $b_1 \dots b_n$ – свободные члены.

СЛАУ можно записать в матричном виде:
$$
\begin{bmatrix}
        a_{11} & a_{12} & \ldots & a_{1n} \\
        a_{21} & a_{22} & \ldots & a_{2n} \\
        \vdots & \vdots & \ddots & \vdots \\
        a_{n1} & a_{n2} & \ldots & a_{nn} \\ 
\end{bmatrix}
\begin{bmatrix}
        x_1 \\
        x_2 \\
        \vdots \\
        x_n\\
\end{bmatrix}
=
\begin{bmatrix}
        b_1 \\
        b_2 \\
        \vdots \\
        b_n\\
\end{bmatrix},
$$
или, если коротко:
$$
\mathbf{AX=B}.
$$,
где $\mathbf{A}$ – матрица коэффициентов (матрица системы), $\mathbf{X}$ – вектор неизвестных, $\mathbf{B}$ – вектор свободных членов.

Напоминаем, что в языке Julia вектор можно задать с помощью символов `[]`, отделяя элементы запятой. Например:

In [3]:
b_1 = [1, 0.5, 4]

3-element Vector{Float64}:
 1.0
 0.5
 4.0

Матрицу можно задать той же командой, отделяя элементы в строке пробелом, а в столбце символом `;`.

In [4]:
A = [1 -2 4;
     2 5 -1;
     4 8 -2]

3×3 Matrix{Int64}:
 1  -2   4
 2   5  -1
 4   8  -2

В Julia есть специальная команда для решения СЛАУ – обратное деление `\`. Пример использования ниже:

In [17]:
A = [1 0; 1 -2]; 
B = [32, -4];
X = A \ B

2-element Vector{Float64}:
 32.0
 18.0

In [10]:
A*X == B

true

Несмотря на то, что Julia есть эта команда, она не всегда эффективно решает СЛАУ, поэтому пока мы будем использовать её только для проверки решений. Мы изучим различные методы решения СЛАУ. Эти методы можно разделить на *прямые* и *итерационные*.

В прямых методах ищется точное решение СЛАУ. В итерационных методах применяется некоторый повторяющийся процесс, который, с каждым новым применением, даёт всё более точное решение.

К прямым методам относятся:
1. Метод Крамера
2. Матричный
3. Метод Гаусса

и др.

Далее разберём метод Гаусса. Он состоит из двух частей: *прямого* хода и *обратного*.

## Метод Гаусса
### Прямой ход
При прямом ходе матрицу $\mathbf{A}$ приводят к верхнетреугольному виду. Для этого из второго уравнения системы вычитают первое, умноженное на коэффициент $\cfrac{a_{21}}{a_{11}}$. Аналогичную процедуру проводят для всех уравнений (строк матрицы). В итоге получим, что все коэффициенты при $x_1$, кроме первого будут равны нулю. Полученная система будет иметь вид:

$$
 \left
\{\begin{gathered}
a_{11}x_1 + a_{12}x_2 + \dots + a_{1n}x_n = b_1 \\
0 + a_{22}x_2 + \dots + a_{2n}x_n = b_2^{(1)} \\
\cdots \\
0 + a_{n2}x_2 + \dots + a_{nn}x_n = b_n^{(1)} \\
\end{gathered}
\right..
$$

Далее из третьего уравнения системы вычитают второе, умноженное на коэффициент $\cfrac{a_{32}}{a_{22}}$, и то же самое делают для всех оставшихся строк. В результате получим следующий вид СЛАУ:

$$
 \left
\{\begin{gathered}
a_{11}x_1 + a_{12}x_2 + a_{13}x_3 + \dots + a_{1n}x_n = b_1 \\
0 + a_{22}x_2 + a_{23}x_2  + \dots + a_{2n}x_n = b_2^{(1)} \\
0 + 0 + a_{33}x_3  + \dots + a_{3n}x_n = b_3^{(2)} \\
\cdots \\
0 + 0 + a_{n3}x_3 + \dots + a_{nn}x_n = b_n^{(2)} \\
\end{gathered}
\right.,
$$

и так далее до тех пор, пока не придём к верхне-треугольному виду:

$$
 \left
\{\begin{gathered}
a_{11}x_1 + a_{12}x_2 + a_{13}x_3 + \dots + a_{1n}x_n = b_1 \\
0 + a_{22}x_2 + a_{23}x_2  + \dots + a_{2n}x_n = b_2^{(1)} \\
0 + 0 + a_{33}x_3  + \dots + a_{3n}x_n = b_3^{(2)} \\
\cdots \\
0 + 0 + 0 + \dots + a_{nn}x_n = b_n^{(n-1)} \\
\end{gathered}
\right..
$$

Если записать, в матричном виде:
$$
\begin{bmatrix}
        a_{11} & a_{12} & \ldots & a_{1n} \\
        0 & a_{22} & \ldots & a_{2n} \\
        \vdots & \vdots & \ddots & \vdots \\
        0 & 0 & \ldots & a_{nn} \\ 
\end{bmatrix}
\begin{bmatrix}
        x_1 \\
        x_2 \\
        \vdots \\
        x_n\\
\end{bmatrix}
=
\begin{bmatrix}
        b_1 \\
        b_2^{(1)} \\
        \vdots \\
        b_n^{(n)}\\
\end{bmatrix}
.
$$

Рассмотрим на примере, как привести к верхне-треугольному виду СЛАУ
$$
\left\{\begin{array}{ccc}2x + y - z &=& 8 \\
-3x - y + 2z &=& -11 \\
-2x + y + 2z &=& -3 \end{array}\right.,
$$
используя средства Julia. Зададим матрицу системы `A` и вектор свободных членов `B`.

In [34]:
A = Float64.([2 1 -1;
              -3 -1 2;
              -2 1 2])

3×3 Matrix{Float64}:
  2.0   1.0  -1.0
 -3.0  -1.0   2.0
 -2.0   1.0   2.0

In [33]:
B = Float64.([8, -11, -3])

3-element Vector{Float64}:
   8.0
 -11.0
  -3.0

Создадим *присоединённую* матрицу (матрицу, состоящую из из матрицы `A`, к которой справа присоединили вектор `B`). Её удобно использовать, чтобы не производить отдельно операции с B.

In [58]:
A_pr = [A B]

3×4 Matrix{Float64}:
  2.0   1.0  -1.0    8.0
 -3.0  -1.0   2.0  -11.0
 -2.0   1.0   2.0   -3.0

Далее, вычтем из второй строки первую, умноженную на $\cfrac{a_{21}}{a_{11}}$. Для этого используем срезы.

In [59]:
A_pr[2, :] -= A_pr[1, :] * A_pr[2,1] / A_pr[1,1];
A_pr

3×4 Matrix{Float64}:
  2.0  1.0  -1.0   8.0
  0.0  0.5   0.5   1.0
 -2.0  1.0   2.0  -3.0

Проделаем аналогичную операцию для третьей строки.

In [60]:
A_pr[3, :] -= A_pr[1, :] * A_pr[3,1] / A_pr[1,1];
A_pr

3×4 Matrix{Float64}:
 2.0  1.0  -1.0  8.0
 0.0  0.5   0.5  1.0
 0.0  2.0   1.0  5.0

Теперь первый столбец заполнен нулями, кроме самого первого элемента. Повторим со вторым столбцом, потребуется вычесть вторую строку всего 1 раз.

In [61]:
A_pr[3, :] -= A_pr[2, :] * A_pr[3,2] / A_pr[2,2];
A_pr

3×4 Matrix{Float64}:
 2.0  1.0  -1.0  8.0
 0.0  0.5   0.5  1.0
 0.0  0.0  -1.0  1.0

### Обратный ход
После прямого хода необходимо выполнить обратный ход, чтобы найти вектор неизвестных. Последний элемент этого вектора - $x_n$ легко найти из последней строки:
$$
x_n = \cfrac{b_n^{(n-1)}}{a_{nn}}.
$$
Соответсвенно, следующий неизвестный элемент можно найти, подставив $x_n$ в предпоследнее уравнение:
$$
x_{n-1} = \cfrac{b_n^{(n-2)}-a_{n-1 n}x_n}{a_{n-1  n-1}},
$$
и так далее. 

Рассмотрим продолжение примера и решим приведённую к треугольному виду СЛАУ. Зададимся вектором неизвестных `X`.

In [64]:
X = Vector{Float64}(undef, 3)

3-element Vector{Float64}:
 8.1498215e-316
 1.61328267e-315
 2.1219957915e-314

Для удобства разделим присоединённую матрицу:

In [69]:
A = A_pr[1:3,1:3];
B = A_pr[1:3, 4];

3-element Vector{Float64}:
 8.0
 1.0
 1.0

Присвоим значение в последний элемент вектора `X`. Для последнего элемента можно использовать индекс `end`

In [70]:
X[end] = B[end]/A[end,end]

-1.0

Далее занесём значение в предпоследний элемент `X`:

In [75]:
X[end-1] = (B[end-1] - A[end-1, end] * X[end]) / A[end-1, end-1]

3.0

Осталось найти последний элемент. Для простоты используем `broadcast` и функцию `sum()`:

In [78]:
X[end-2] = (B[end-2] - sum(A[end-2, end-1:end] .* X[end-1:end]))/A[end-2, end-2];
X

3-element Vector{Float64}:
  2.0
  3.0
 -1.0

Проверяем:

In [79]:
A\B == X

true

### Упражнение 1
Создать функцию `uptri(M::AbstractMatrix)`, которая из заданной матрицы делает верхнетреугольную.

In [83]:
function uptri(M::AbstractMatrix)
    
    # сначала скопируйте матрицу в отдельную переменную А, чтобы не изменять исходную матрицу

    
    # желательно узнать число строк матрицы. Это можно сделать с помощью команды size(M)

    
    # здесь задайте основной цикл. Из каждой строчки надо вычесть i-ю, умноженную на соответствующий коэффициент
    
    # Верните матрицу A
    return A
end

uptri (generic function with 1 method)

In [120]:
function uptri(M::AbstractMatrix)
    A = copy(M)
    n = size(A)[1]
    for i in 1:n-1
        for j in i+1:n
            A[j, :] .-= A[i, :] / A[i, i] * A[j, i]
        end
    end
    return A
end

uptri (generic function with 1 method)

### Упражнение 2
Создать функцию `gauss(A::AbstractMatrix,B::AbstractVector)::Vector{Float64}`, которая находит решение СЛАУ с матрицей `A` и вектором `B` методом Гаусса. Можно использовать уже имеющуюся функцию `uptri`.

In [ ]:
function gauss(A::AbstractMatrix, B::AbstractVector)::Vector{Float64}
    
    # желательно узнать число строк матрицы. Это можно сделать с помощью команды size(A)


    # Задайте заранее вектор X


    # С помощью функции uptri сделайте прямой ход для присоединённой матрицы


    # Разделите полученную матрицу на матрицы A и B

    
    # Посчитайте X[n]

    
    # Сделайте цикл обратного хода для i от (n-1) до 1

    
    # Верните вектор X
end

In [169]:
function gauss(A::AbstractMatrix, B::AbstractVector)::Vector{Float64}
    n = size(A)[1]
    X = zeros(Float64, n)
    
    A_pr = uptri([A B])
    A_new = A_pr[1:end, 1:end-1]
    B_new = A_pr[1:end, end]
    
    X[n] = B_new[n]/A_new[n, n]
    for i in n-1:-1:1
        X[i] = (B_new[i] - sum(A_new[i, i+1:n] .* X[i+1:n]))/A_new[i,i]
    end
    return X
end

gauss (generic function with 1 method)